# The version of the .ohwr.yaml schema.
version: '1.0.0'
# The name of your project.
name: 'Everything PMOD'
# Link to the Markdown description of your project. The
# description is read from the first section of the file.
description: 'https://github.com/I2SenseLab/TT-EverythingPMOD/blob/main/README.md'
# The website of your project. Use the web page of your git repository if
# your project doesn't have website (e.g. 'https://github.com/user/project').
website: 'https://github.com/I2SenseLab/TT-EverythingPMOD'
# (optional) The licenses of your project. SPDX IDs: https://spdx.org/licenses.
# licenses: ['CERN-OHL-W-2.0+']
# # (optional) Images of your project (maximum 5 images). The main image should
# # be the first in the list (e.g. a photo of the latest prototype).
# images:
#   - 'https://your.project.com/img1.png'
#   - 'https://your.project.com/img2.png'
# # (optional) Link to the documentation of your project.
# documentation: 'https://github.com/user/project/wiki'
# # (optional) Link to the issue/bug tracker of your project.
# issues: 'https://github.com/user/project/issues'
# # (optional) Link to the latest release of your project.
# latest_release: 'https://github.com/user/project/releases/latest'
# # (optional) Link to the forum where your community has conversations.
# forum: 'https://forums.ohwr.org/c/project'
# # (optional) Link to the Markdown newsfeed of your project.
# newsfeed: 'https://raw.githubusercontent.com/wiki/user/project/news.md'
# # (optional) Addtional links.
# links:
#   - name: 'Link text here'
#     url: 'https://foo.com/bar1'
#   - name: 'Link text here'
#     url: 'https://foo.com/bar2'