// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// mirror_single //
// ------------- //

#define mirror_single_wrap_target 0
#define mirror_single_wrap 3
#define mirror_single_pio_version 1

static const uint16_t mirror_single_program_instructions[] = {
            //     .wrap_target
    0x4001, //  0: in     pins, 1
    0xa0e6, //  1: mov    osr, isr
    0x6001, //  2: out    pins, 1
    0x0000, //  3: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program mirror_single_program = {
    .instructions = mirror_single_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = mirror_single_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config mirror_single_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + mirror_single_wrap_target, offset + mirror_single_wrap);
    return c;
}
#endif

